# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
title: calavera.info
url: "http://calavera.info" # the base hostname & protocol for your site
permalink: /v3/blog/:year/:month/:day/:title.html
baseurl: "" # the subpath of your site, e.g. /blog
# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: "_posts/en"
      type: "posts"
    values:
      layout: "post"
      lang: en
  -
    scope:
      path: "_posts/cs"
      type: "posts"
    values:
      layout: "post"
      lang: cs
  -
    scope:
      path: "v3/en"
      type: "pages"
    values:
      layout: "page"
      lang: en
  -
    scope:
      path: "v3/cs"
      type: "pages"
    values:
      layout: "page"
      lang: cs
